### ISSUE TITLE
CancelOrderAsync method throws an exception with message "Sequence contains no elements"

### ISSUE THREAD

**Issue by deroc77** [JKorf/Bittrex.Net#203]
**Describe the bug**
CancelOrderAsync method throws an exception with message "Sequence contains no elements" (version 6.1.0)

**To Reproduce**
1. Create bittrex client (OK)
2. Set api and secret keys using SetApiCredentials method (OK)
3. Create trade order using PlaceOrderAsync method (OK, i can see my new order in bittrex exchange ui)
4. Try to cancel order using CancelOrderAsync (ERROR)

**Expected behavior**
The previously created order will be successfully canceled 

**Debug logging**
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Bittrex.Net.BittrexAuthenticationProvider.AddAuthenticationToHeaders(String uri, HttpMethod method, Dictionary`2 parameters, Boolean signed, HttpMethodParameterPosition parameterPosition, ArrayParametersSerialization arraySerialization)
   at CryptoExchange.Net.RestClient.ConstructRequest(Uri uri, HttpMethod method, Dictionary`2 parameters, Boolean signed, HttpMethodParameterPosition parameterPosition, ArrayParametersSerialization arraySerialization, Int32 requestId, Dictionary`2 additionalHeaders)
   at CryptoExchange.Net.RestClient.SendRequestAsync[T](Uri uri, HttpMethod method, CancellationToken cancellationToken, Dictionary`2 parameters, Boolean signed, Boolean checkResult, Nullable`1 parameterPosition, Nullable`1 arraySerialization, Int32 credits, JsonSerializer deserializer, Dictionary`2 additionalHeaders)
   at Bittrex.Net.BittrexClient.CancelOrderAsync(String orderId, CancellationToken ct)

**Comment by JKorf** [comment]
I've pushed a new version which should fix this issue
