### ISSUE TITLE
NullReferenceException when the network is offline

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#39]
Hi, I'm testing the client error handling on disconnected network and I gen a NullReferenceException from the method `GetLatestCandleAsync`. Seems it comes from protected method `ExecuteRequest`. Here's the exception trace:

`   at Bittrex.Net.BittrexClient.<ExecuteRequest>d__86`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Bittrex.Net.BittrexClient.<ExecuteRequest>d__86`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Bittrex.Net.BittrexClient.<ExecuteRequest>d__86`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Bittrex.Net.BittrexClient.<GetLatestCandleAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CryptoService.Data.Services.BittrexService.<>c__DisplayClass13_1.<<GetMarketStateAsync>b__0>d.MoveNext() in C:\Users\andrew.sloven\Workspaces\CryptoSwag\CryptoService\CryptoService.Data\Services\BittrexService.cs:line 177`

**Comment by JKorf** [comment]
I've found the issue, fix will be in next release

**Comment by JKorf** [comment]
Fixed in latest release
