### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by grant-d** [JKorf/Bittrex.Net#78]
When using the (integration test) code below, I *sometimes* get the following:
`InvalidOperationException` : `Sequence contains no matching element`

```
// Intentionally placing limit way below current price of 0.00000044 so as to avoid any actual sells
var result = await client.PlaceConditionalOrderAsync(OrderSide.Sell, TimeInEffect.GoodTillCancelled, Ladder.Market.Name, 6000, 0.00000010m, ConditionType.LessThan, 0.00000020m);
```

The order *does* get created on Bittrex - and all its parameters are set correctly.
So I think the request is fine, it (maybe) has something to do with how you are parsing the returned json.

I have looked through the CryptoExchange.Net.ExchangeClient underlying lib, and can't find any misuse of (eg) `FirstOrDefault`. Maybe it's coming from the base class you have for `BaseConverter`, where you use `Single` a few times (vs `SingleOrDefault`)? My reasoning is that the top of the stack is this line, which would seem to imply your custom converter logic is being called:

`at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(...)`

I will find some time to clone your repos and debug my side too.

Debug Output:
```
08:52:56:018 | Debug | Sending  request to https://www.bittrex.com/api/v1.1/public/getticker?market=BTC-DOGE
08:52:56:233 | Debug | Sending signed request to https://www.bittrex.com/api/v2.0/key/market/tradesell?ordertype=Limit&timeineffect=GOOD_TIL_CANCELLED&marketname=BTC-DOGE&quantity=6000&rate=0.00000010&conditiontype=LESS_THAN&target=0.00000020&apiKey=<elided>&nonce=<elided>
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Sequence contains no matching element
```

Stack trace:
```   
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at CryptoExchange.Net.BaseConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at CryptoExchange.Net.ExchangeClient.Deserialize[T](String data, Boolean checkObject)
   at CryptoExchange.Net.ExchangeClient.<ExecuteRequest>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Bittrex.Net.BittrexClient.<Execute>d__79`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Bittrex.Net.BittrexClient.<PlaceConditionalOrderAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BarbetLane.Manage.StopLossMachine.<FooAsync>d__4.MoveNext() in C:\Repos\BarbetLane\BarbetLane\Manage\StopLossMachine.cs:line 22
```

**Comment by grant-d** [comment]
Here's the code I am referring to. Either the `.Single` calls are failing to find the predicate, or maybe it's due to the missing `.Key` below?

```
public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var val = Mapping.Single(v => v.Value == reader.Value.ToString()).Key;
            if (val != null)
                return val;
            return Mapping.Single(v => v.Value.ToLower() == reader.Value.ToString().ToLower()); // Might be missing .Key?
        }

        public T ReadString(string data)
        {
            return Mapping.Single(v => v.Value == data).Key;
        }
```

**Comment by JKorf** [comment]
Hi, you're actually right with your second comment, it should be `.Key`, however the original error happens in
````C#
var val = Mapping.Single(v => v.Value == reader.Value.ToString()).Key;
            if (val != null)
                return val;
````
That single should be a SingleOrDefault. I'll push a fix somewhere today. Thanks for reporting and helping debugging it!

**Comment by JKorf** [comment]
Should be fixed in the latest version

**Comment by grant-d** [comment]
No problem, thanks for jumping on this so quick
